kernel: pse-pd: Fix missing regulator backport
Fixes: 528c9259a70f Backport the PSE-PD...

When the original backport bring-in was done, the regulator power budget
portion was missed.  This results in kernel build errors when trying to
bring in PSE_CONTROLLER or PSE_REGULATOR configs.  Which are required to
bring in further PSE drivers.
Bring in the backport to fix that up.  Patch series naming is a bit wrong
here, but keeps patches together in ordering, whilst reducing files
touched in this commit.

Without this patch, when adding config of
CONFIG_PSE_CONTROLLER=y
CONFIG_PSE_REGULATOR=y
CONFIG_PSE_TPS23881=y
CONFIG_REGULATOR=y

The following errors occur:
drivers/net/pse-pd/pse_core.c:446:9:
  error: implicit declaration of function 'regulator_free_power_budget'

drivers/net/pse-pd/pse_core.c:559:16:
  error: implicit declaration of function 'regulator_request_power_budget'

Signed-off-by: Bevan Weiss <bevan.weiss@gmail.com>
Link: https://github.com/openwrt/openwrt/pull/21996
Signed-off-by: Robert Marko <robimarko@gmail.com>