bcm27xx: update irq-msi-lib.h header path
Fix build error:

drivers/irqchip/irq-bcm2712-mip.c:14:10: fatal error: irq-msi-lib.h: No such file or directory
   14 | #include "irq-msi-lib.h"
      |          ^~~~~~~~~~~~~~~

Fixes: ba7aa2a97153 ("generic: backport MSI affinity support for DW PCIe")
Signed-off-by: Shiji Yang <yangshiji66@outlook.com>
Link: https://github.com/openwrt/openwrt/pull/23125
Signed-off-by: Robert Marko <robimarko@gmail.com>